import {
  RiAncientGateFill,
  RiCloudFill,
  RiScissors2Fill,
  RiMagicFill,
  RiBatteryChargeFill,
  RiKeynoteFill,
  RiShoppingBagFill,
  RiShoppingCart2Fill,
  RiVipCrown2Fill,
  RiBikeFill,
  RiEBike2Fill,
  RiGasStationFill,
  RiRidingFill,
  RiRocketFill,
  RiTaxiFill,
  RiCameraFill,
  RiImage2Fill,
  RiCactusFill,
  RiKey2Fill,
  RiUmbrellaFill,
  RiMoonFill,
  RiSunFill,
  RiStarFill,
  RiPlantFill,
  RiRadioFill,
  RiHeadphoneFill,
  RiSailboatFill,
  RiEarthFill,
  RiMailFill,
  RiQuestionMark,
} from "react-icons/ri";


export const gameIconPack = [
  RiAncientGateFill,
  RiCloudFill,
  RiScissors2Fill,
  RiMagicFill,
  RiBatteryChargeFill,
  RiKeynoteFill,
  RiShoppingBagFill,
  RiShoppingCart2Fill,
  RiVipCrown2Fill,
  RiBikeFill,
  RiEBike2Fill,
  RiGasStationFill,
  RiRidingFill,
  RiRocketFill,
  RiTaxiFill,
  RiCameraFill,
  RiImage2Fill,
  RiCactusFill,
  RiKey2Fill,
  RiUmbrellaFill,
  RiMoonFill,
  RiSunFill,
  RiStarFill,
  RiPlantFill,
  RiRadioFill,
  RiHeadphoneFill,
  RiSailboatFill,
  RiEarthFill,
  RiMailFill,
];

export const QuestionMark = RiQuestionMark;
